const BEAT_VH = 60;
const SUBTITLE_BEAT_COUNT = 4;
const INTRO_VH = BEAT_VH * SUBTITLE_BEAT_COUNT;

const CAPTION_VH = 30;
const CAPTION_COUNT = 4;
const CAPTIONS_VH = CAPTION_VH * CAPTION_COUNT;

export const PLUNGE_VH = BEAT_VH * 4;

export const TOTAL_VH = INTRO_VH + CAPTIONS_VH + PLUNGE_VH;

export const SUBTITLE_STORY_END = INTRO_VH / TOTAL_VH;
export const PLUNGE_START = (INTRO_VH + CAPTIONS_VH) / TOTAL_VH;
